name: Validate code against standards
on: push
defaults:
  run:
    shell: bash

jobs:
  composer_validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
